### ISSUE TITLE
Got an error while training.

### ISSUE THREAD

**Issue by zgxiangyang** [royorel/Lifespan_Age_Transformation_Synthesis#6]
```
Original Traceback (most recent call last):
  File "/home/myname/anaconda3/envs/py37_v2/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/myname/anaconda3/envs/py37_v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/myname/Lifespan_Age_Transformation_Synthesis/models/networks.py", line 799, in forward
    gan_out = self.gan_head(self.minibatch_stdev(features))
  File "/home/myname/Lifespan_Age_Transformation_Synthesis/models/networks.py", line 794, in minibatch_stdev
    out = torch.cat((input, mean_std), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 5 in dimension 2 at /opt/conda/conda-bld/pytorch_1573049306803/work/aten/src/THC/generic/THCTensorMath.cu:71
```

**Comment by royorel** [comment]
Did you train on 256x256 images or a different size?

**Comment by zgxiangyang** [comment]
Sorry, I used another size by accident.

**Comment by royorel** [comment]
I fixed the minibatch_stdev code to support all image sizes in commit 29f5afa
